#!/usr/bin/python
# 18500 Capstone S20
# Eric Chen, Alton Olsen, Deanyone Su
#
# Short python script to generate RGB values from a local image

from scipy import misc
from sys import argv

# get filename from command line, get RGBA values
img_matrix = misc.imread(argv[1])
color_matrix = []

# scan through img_matrix and scale RGB values by A/255
row_count = len(img_matrix)
col_count = len(img_matrix[0])
for i in xrange(row_count):
    for j in xrange(col_count):
        alpha = img_matrix[i][j][3] / 255
        red_value = hex(int(img_matrix[i][j][0] * alpha)).strip('0x').zfill(2)
        green_value = hex(int(img_matrix[i][j][1] * alpha)).strip('0x').zfill(2)
        blue_value = hex(int(img_matrix[i][j][2] * alpha)).strip('0x').zfill(2)
        # print("Row %d, Col %d" % (i, j))
        # print(red_value)
        # print(green_value)
        # print(blue_value)
        # print("\n")
        color_matrix.append("".join([red_value, green_value, blue_value]))
# write .mif file
if (argv[2][-4:] != '.mif'):
    print('Provided output file is not .mif file')
    exit()
mif_file = open(argv[2], 'w');
write_contents = ['%\n']
write_contents.append('18500 Capstone S20\n')
write_contents.append('Eric Chen, Alton Olsen, Deanyone Su\n\n')
write_contents.append('This is an autogenerated .mif file containing color ' + \
    'data stripped from a\nprovided local image\n')
write_contents.append('%\n\n')

write_contents.append('DEPTH = %d;\n' % ((i+1) * (j+1)))
write_contents.append('WIDTH = 24;\n')
write_contents.append('ADDRESS_RADIX = DEC;\n')
write_contents.append('DATA_RADIX = HEX;\n')
write_contents.append('CONTENT BEGIN\n\n')

for color_idx in xrange(len(color_matrix)):
    write_contents.append("%d : %s;\n" % (color_idx, color_matrix[color_idx]))

write_contents.append('\nEND;\n')
mif_file.writelines(write_contents)
mif_file.close()